cutscenename="BAHATI"
cutsceneline="WELL LOOK AT' ER, SHE ALREADY HAD\nENOUGH. AGGRESSIVE INTERROGATION\nDOESN'T ALWAYS WORK. HAVEN'T YA SEEN IT\nIN THE PICTURES?"

with diva3 {image_speed=0.1 image_index=0}
