if specialcheck5=0
{cutscenename="VIVA"
cutsceneline="NOW THAT'S JUST RIDICULOUS, HOW'S THAT GONNA HELP?"}
if specialcheck5=1
{cutscenename="SOFIA"
cutsceneline="WHAT DO YOU MEAN?! IT'S A GOOD IDEA!"}
if specialcheck5=2
{cutscenename="BAHATI"
cutsceneline="THAT SOUNDS SILLY BUT... IT'S A LITTLE"}
if specialcheck5=3
{cutscenename="HINA"
cutsceneline="I LIKE THAT PLAN THO... BUT HEY"}
if specialcheck5=4
{cutscenename="VIVA"
cutsceneline="HEY I HAVE A BETTER PLAN! AND IT'S ABOUT"}
if specialcheck5=5
{cutscenename="SOFIA"
cutsceneline="NO I HAVE A BETTER PLAN! AND IT'S "}
if specialcheck5=6
{cutscenename="HINA"
cutsceneline="UH... LADIES?"}
if specialcheck5=7
{cutscenename="BAHATI"
cutsceneline="I HAVE AN IDEA! AND I AM GONNA"}
if specialcheck5=8
{cutscenename=""
cutsceneline="(ARGUMENTS ENSUE)"}

specialcheck5+=1

if specialcheck5!=12
timeline_position-=50
