function hiscore_save(){
ini_open("GAMEDATA/hiscore.ini");
ini_write_real("HIGHSCORE1", "SCORE", global.HiScore1)
ini_write_string("HIGHSCORE1", "NAME", global.HiScoreName1)
ini_write_real("HIGHSCORE1", "FACE", global.HiScoreFace1)
ini_write_real("HIGHSCORE1", "STAGE", global.HiScoreStage1)
ini_write_real("HIGHSCORE2", "SCORE", global.HiScore2)
ini_write_string("HIGHSCORE2", "NAME", global.HiScoreName2)
ini_write_real("HIGHSCORE2", "FACE", global.HiScoreFace2)
ini_write_real("HIGHSCORE2", "STAGE", global.HiScoreStage2)
ini_write_real("HIGHSCORE3", "SCORE", global.HiScore3)
ini_write_string("HIGHSCORE3", "NAME", global.HiScoreName3)
ini_write_real("HIGHSCORE3", "FACE", global.HiScoreFace3)
ini_write_real("HIGHSCORE3", "STAGE", global.HiScoreStage3)
ini_write_real("HIGHSCORE4", "SCORE", global.HiScore4)
ini_write_string("HIGHSCORE4", "NAME", global.HiScoreName4)
ini_write_real("HIGHSCORE4", "FACE", global.HiScoreFace4)
ini_write_real("HIGHSCORE4", "STAGE", global.HiScoreStage4)
ini_write_real("HIGHSCORE5", "SCORE", global.HiScore5)
ini_write_string("HIGHSCORE5", "NAME", global.HiScoreName5)
ini_write_real("HIGHSCORE5", "FACE", global.HiScoreFace5)
ini_write_real("HIGHSCORE5", "STAGE", global.HiScoreStage5)
ini_write_real("HIGHSCORE6", "SCORE", global.HiScore6)
ini_write_string("HIGHSCORE6", "NAME", global.HiScoreName6)
ini_write_real("HIGHSCORE6", "FACE", global.HiScoreFace6)
ini_write_real("HIGHSCORE6", "STAGE", global.HiScoreStage6)
ini_write_real("HIGHSCORE7", "SCORE", global.HiScore7)
ini_write_string("HIGHSCORE7", "NAME", global.HiScoreName7)
ini_write_real("HIGHSCORE7", "FACE", global.HiScoreFace7)
ini_write_real("HIGHSCORE7", "STAGE", global.HiScoreStage7)
ini_write_real("HIGHSCORE8", "SCORE", global.HiScore8)
ini_write_string("HIGHSCORE8", "NAME", global.HiScoreName8)
ini_write_real("HIGHSCORE8", "FACE", global.HiScoreFace8)
ini_write_real("HIGHSCORE8", "STAGE", global.HiScoreStage8)
ini_write_real("HIGHSCORE9", "SCORE", global.HiScore9)
ini_write_string("HIGHSCORE9", "NAME", global.HiScoreName9)
ini_write_real("HIGHSCORE9", "FACE", global.HiScoreFace9)
ini_write_real("HIGHSCORE9", "STAGE", global.HiScoreStage9)
ini_write_real("HIGHSCORE10", "SCORE", global.HiScore10)
ini_write_string("HIGHSCORE10", "NAME", global.HiScoreName10)
ini_write_real("HIGHSCORE10", "FACE", global.HiScoreFace10)
ini_write_real("HIGHSCORE10", "STAGE", global.HiScoreStage10)

ini_close()
}
