// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information
function soundtest_sounds(){
switch (soundno)
{
case 1: soundname="SND 1" playSFX=snd_1up voiceActor="" break;
case 2: soundname="SND 2" playSFX=snd_beat voiceActor="" break;
case 3: soundname="SND 3" playSFX=snd_beep voiceActor="" break;
case 4: soundname="SND 4" playSFX=snd_bigpowerup voiceActor="" break;
case 5: soundname="SND 5" playSFX=snd_bonebreak voiceActor="" break;
case 6: soundname="SND 6" playSFX=snd_bubblefire voiceActor="" break;
case 7: soundname="SND 7" playSFX=snd_bull voiceActor="" break;
case 8: soundname="SND 8" playSFX=snd_crumbles voiceActor="" break;
case 9: soundname="SND 9" playSFX=snd_crumblem voiceActor="" break;
case 10: soundname="SND 10" playSFX=snd_crumblel voiceActor="" break;
case 11: soundname="SND 11" playSFX=snd_drum voiceActor="" break;
case 12: soundname="SND 12" playSFX=snd_eat voiceActor="" break;
case 13: soundname="SND 13" playSFX=snd_ex voiceActor="" break;
case 14: soundname="SND 14" playSFX=snd_exs voiceActor="" break;
case 15: soundname="SND 15" playSFX=snd_film1 voiceActor="" break;
case 16: soundname="SND 16" playSFX=snd_film2 voiceActor="" break;
case 17: soundname="SND 17" playSFX=snd_flameshort voiceActor="" break;
case 18: soundname="SND 18" playSFX=snd_flame voiceActor="" break;
case 19: soundname="SND 19" playSFX=snd_flamelong voiceActor="" break;
case 20: soundname="SND 20" playSFX=snd_glassbreaks voiceActor="" break;
case 21: soundname="SND 21" playSFX=snd_glassbreakm voiceActor="" break;
case 22: soundname="SND 22" playSFX=snd_glassbreakl voiceActor="" break;
case 23: soundname="SND 23" playSFX=snd_glassexs voiceActor="" break;
case 24: soundname="SND 24" playSFX=snd_glassex voiceActor="" break;
case 25: soundname="SND 25" playSFX=snd_gong voiceActor="" break;
case 26: soundname="SND 26" playSFX=snd_hop1 voiceActor="" break;
case 27: soundname="SND 27" playSFX=snd_magic1 voiceActor="" break;
case 28: soundname="SND 28" playSFX=snd_magic2 voiceActor="" break;
case 29: soundname="SND 29" playSFX=snd_magic3 voiceActor="" break;
case 30: soundname="SND 30" playSFX=snd_metalbreaks voiceActor="" break;
case 31: soundname="SND 31" playSFX=snd_metalbreakm voiceActor="" break;
case 32: soundname="SND 32" playSFX=snd_metalbreakl voiceActor="" break;
case 33: soundname="SND 33" playSFX=snd_metalexs voiceActor="" break;
case 34: soundname="SND 34" playSFX=snd_metalex voiceActor="" break;
case 35: soundname="SND 35" playSFX=snd_mirrorfx1 voiceActor="" break;
case 36: soundname="SND 36" playSFX=snd_mirrorfx2 voiceActor="" break;
case 37: soundname="SND 37" playSFX=snd_select voiceActor="" break;
case 38: soundname="SND 38" playSFX=snd_picked voiceActor="" break;
case 39: soundname="SND 39" playSFX=snd_quakeground voiceActor="" break;
case 40: soundname="SND 40" playSFX=snd_quicksand voiceActor="" break;
case 41: soundname="SND 41" playSFX=snd_shrink voiceActor="" break;
case 42: soundname="SND 42" playSFX=snd_splash1 voiceActor="" break;
case 43: soundname="SND 43" playSFX=snd_splash2 voiceActor="" break;
case 44: soundname="SND 44" playSFX=snd_splash3 voiceActor="" break;
case 45: soundname="SND 45" playSFX=snd_splash4 voiceActor="" break;
case 46: soundname="SND 46" playSFX=snd_splash5 voiceActor="" break;
case 47: soundname="SND 47" playSFX=snd_steal voiceActor="" break;
case 48: soundname="SND 48" playSFX=snd_stonebreaks voiceActor="" break;
case 49: soundname="SND 49" playSFX=snd_stonebreakm voiceActor="" break;
case 50: soundname="SND 50" playSFX=snd_stonebreakl voiceActor="" break;
case 51: soundname="SND 51" playSFX=snd_stoneexs voiceActor="" break;
case 52: soundname="SND 52" playSFX=snd_stoneex voiceActor="" break;
case 53: soundname="SND 53" playSFX=snd_thunder voiceActor="" break;
case 54: soundname="SND 54" playSFX=snd_thunderclap voiceActor="" break;
case 55: soundname="SND 55" playSFX=snd_thunderclap2 voiceActor="" break;
case 56: soundname="SND 56" playSFX=snd_train voiceActor="" break;
case 57: soundname="SND 57" playSFX=snd_tremor voiceActor="" break;
case 58: soundname="SND 58" playSFX=snd_tremor2 voiceActor="" break;
case 59: soundname="SND 59" playSFX=snd_ufo1 voiceActor="" break;
case 60: soundname="SND 60" playSFX=snd_ufo2 voiceActor="" break;
case 61: soundname="SND 61" playSFX=snd_wind voiceActor="" break;
case 62: soundname="SND 62" playSFX=snd_wind2 voiceActor="" break;
case 63: soundname="SND 63" playSFX=snd_woodbreaks voiceActor="" break;
case 64: soundname="SND 64" playSFX=snd_woodbreakm voiceActor="" break;
case 65: soundname="SND 65" playSFX=snd_woodbreakl voiceActor="" break;

///snd_titlescreen - Viva

case 66: soundname="SND 66" playSFX=snd_cut voiceActor="" break;
case 67: soundname="SND 67" playSFX=snd_explosion voiceActor="" break;
case 68: soundname="SND 68" playSFX=snd_explosion2 voiceActor="" break;
case 69: soundname="SND 69" playSFX=snd_food voiceActor="" break;
case 70: soundname="SND 70" playSFX=snd_getweapon voiceActor="" break;
case 71: soundname="SND 71" playSFX=snd_gun voiceActor="" break;
case 72: soundname="SND 72" playSFX=snd_handgun voiceActor="" break;
case 73: soundname="SND 73" playSFX=snd_metalhit voiceActor="" break;
case 74: soundname="SND 74" playSFX=snd_pickitem voiceActor="" break;
case 75: soundname="SND 75" playSFX=snd_smoke voiceActor="" break;

case 76: soundname="SND 76" playSFX=snd_alien1 voiceActor="" break;
case 77: soundname="SND 77" playSFX=snd_alien2 voiceActor="" break;
case 78: soundname="SND 78" playSFX=snd_bounce voiceActor="" break;
case 79: soundname="SND 79" playSFX=snd_break voiceActor="" break;
case 80: soundname="SND 80" playSFX=snd_break2 voiceActor="" break;
case 81: soundname="SND 81" playSFX=snd_carengine voiceActor="" break;
case 82: soundname="SND 82" playSFX=snd_carengine2 voiceActor="" break;
case 83: soundname="SND 83" playSFX=snd_carengine3 voiceActor="" break;
case 84: soundname="SND 84" playSFX=snd_creak voiceActor="" break;
case 85: soundname="SND 85" playSFX=snd_dashing voiceActor="" break;
case 86: soundname="SND 86" playSFX=snd_fall voiceActor="" break;
case 87: soundname="SND 87" playSFX=snd_go voiceActor="" break;
case 88: soundname="SND 88" playSFX=snd_heavystep voiceActor="" break;
case 89: soundname="SND 89" playSFX=snd_hit voiceActor="" break;
case 90: soundname="SND 90" playSFX=snd_hit2 voiceActor="" break;
case 91: soundname="SND 91" playSFX=snd_hit3 voiceActor="" break;
case 92: soundname="SND 92" playSFX=snd_hit4 voiceActor="" break;
case 93: soundname="SND 93" playSFX=snd_hit5 voiceActor="" break;
case 94: soundname="SND 94" playSFX=snd_hitground voiceActor="" break;
case 95: soundname="SND 95" playSFX=snd_hitgroundheavy voiceActor="" break;
case 96: soundname="SND 96" playSFX=snd_hitgroundmetal voiceActor="" break;
case 97: soundname="SND 97" playSFX=snd_homerun voiceActor="" break;
case 98: soundname="SND 98" playSFX=snd_jump voiceActor="" break;
case 99: soundname="SND 99" playSFX=snd_land voiceActor="" break;
case 100: soundname="SND 100" playSFX=snd_laserbeam voiceActor="" break;
case 101: soundname="SND 101" playSFX=snd_melthit voiceActor="" break;
case 102: soundname="SND 102" playSFX=snd_shocked voiceActor="" break;
case 103: soundname="SND 103" playSFX=snd_shocked2 voiceActor="" break;
case 104: soundname="SND 104" playSFX=snd_shocked3 voiceActor="" break;
case 105: soundname="SND 105" playSFX=snd_shotgun voiceActor="" break;
case 106: soundname="SND 106" playSFX=snd_swing voiceActor="" break;
case 107: soundname="SND 107" playSFX=snd_swing2 voiceActor="" break;
case 108: soundname="SND 108" playSFX=snd_swing3 voiceActor="" break;
case 109: soundname="SND 109" playSFX=snd_swing4 voiceActor="" break;
case 110: soundname="SND 110" playSFX=snd_swing5 voiceActor="" break;
case 111: soundname="SND 111" playSFX=snd_squeaky voiceActor="" break;
case 112: soundname="SND 112" playSFX=snd_coconut voiceActor="" break;


case 113: soundname="VIVA 1" playSFX=snd_viva1 voiceActor="" break;
case 114: soundname="VIVA 2" playSFX=snd_viva2 voiceActor="" break;
case 115: soundname="VIVA 3" playSFX=snd_viva3 voiceActor="" break;
case 116: soundname="VIVA 4" playSFX=snd_viva4 voiceActor="" break;
case 117: soundname="VIVA 5" playSFX=snd_viva5 voiceActor="" break;
case 118: soundname="VIVA 6" playSFX=snd_viva6 voiceActor="" break;
case 119: soundname="VIVA 7" playSFX=snd_viva7 voiceActor="" break;
case 120: soundname="VIVA 8" playSFX=snd_viva8 voiceActor="" break;
case 121: soundname="VIVA 9" playSFX=snd_viva9 voiceActor="" break;
case 122: soundname="VIVA 10" playSFX=snd_viva10 voiceActor="" break;
case 123: soundname="VIVA 11" playSFX=snd_viva11 voiceActor="" break;
case 124: soundname="VIVA 12" playSFX=snd_viva12 voiceActor="" break;
case 125: soundname="VIVA 13" playSFX=snd_viva13 voiceActor="" break;
case 126: soundname="VIVA 14" playSFX=snd_vivanoise voiceActor="" break;
case 127: soundname="VIVA 15" playSFX=snd_VivaScream voiceActor="" break;
case 128: soundname="VIVA 16" playSFX=snd_VivaSing1 voiceActor="" break;
case 129: soundname="VIVA 17" playSFX=snd_VivaSing2 voiceActor="" break;
case 130: soundname="VIVA 18" playSFX=snd_VivaSing3 voiceActor="" break;
case 131: soundname="VIVA 19" playSFX=snd_viva20 voiceActor="" break;
case 132: soundname="VIVA 20" playSFX=snd_viva21 voiceActor="" break;
case 133: soundname="VIVA 21" playSFX=snd_titlescreen voiceActor="" break;

case 134: soundname="HINA 1" playSFX=snd_hina1 voiceActor="" break;
case 135: soundname="HINA 2" playSFX=snd_hina2 voiceActor="" break;
case 136: soundname="HINA 3" playSFX=snd_hina3 voiceActor="" break;
case 137: soundname="HINA 4" playSFX=snd_hina4 voiceActor="" break;
case 138: soundname="HINA 5" playSFX=snd_hina5 voiceActor="" break;
case 139: soundname="HINA 6" playSFX=snd_hina6 voiceActor="" break;
case 140: soundname="HINA 7" playSFX=snd_hina7 voiceActor="" break;
case 141: soundname="HINA 8" playSFX=snd_hina8 voiceActor="" break;
case 142: soundname="HINA 9" playSFX=snd_hina9 voiceActor="" break;
case 143: soundname="HINA 10" playSFX=snd_hina10 voiceActor="" break;
case 144: soundname="HINA 11" playSFX=snd_hina11 voiceActor="" break;
case 145: soundname="HINA 12" playSFX=snd_hina12 voiceActor="" break;
case 146: soundname="HINA 13" playSFX=snd_hina13 voiceActor="" break;
case 147: soundname="HINA 14" playSFX=snd_Hina_ComeOn voiceActor="" break;
case 148: soundname="HINA 15" playSFX=snd_Hina_Subarashi voiceActor="" break;
case 149: soundname="HINA 16" playSFX=snd_Hina_YouDidGreat voiceActor="" break;
case 150: soundname="HINA 17" playSFX=snd_hina20 voiceActor="" break;
case 151: soundname="HINA 18" playSFX=snd_hina21 voiceActor="" break;
case 152: soundname="HINA 19" playSFX=snd_HinaScream voiceActor="" break;
case 153: soundname="HINA 20" playSFX=snd_HinaSing1 voiceActor="" break;
case 154: soundname="HINA 21" playSFX=snd_HinaSing2 voiceActor="" break;
case 155: soundname="HINA 22" playSFX=snd_HinaSing3 voiceActor="" break;
case 156: soundname="HINA 23" playSFX=snd_titlescreen2 voiceActor="" break;

case 157: soundname="BAHATI 1" playSFX=snd_bahati5 voiceActor="" break;
case 158: soundname="BAHATI 2" playSFX=snd_bahati6 voiceActor="" break;
case 159: soundname="BAHATI 3" playSFX=snd_bahati7 voiceActor="" break;
case 160: soundname="BAHATI 4" playSFX=snd_bahati8 voiceActor="" break;
case 161: soundname="BAHATI 5" playSFX=snd_bahati9 voiceActor="" break;
case 162: soundname="BAHATI 6" playSFX=snd_bahati10 voiceActor="" break;
case 163: soundname="BAHATI 7" playSFX=snd_bahati11 voiceActor="" break;
case 164: soundname="BAHATI 8" playSFX=snd_bahati12 voiceActor="" break;
case 165: soundname="BAHATI 9" playSFX=snd_bahati13 voiceActor="" break;
case 166: soundname="BAHATI 10" playSFX=snd_bahati14 voiceActor="" break;
case 167: soundname="BAHATI 11" playSFX=snd_bahati20 voiceActor="" break;
case 168: soundname="BAHATI 12" playSFX=snd_bahati21 voiceActor="" break;
case 169: soundname="BAHATI 13" playSFX=snd_BahatiScream voiceActor="" break;
case 170: soundname="BAHATI 14" playSFX=snd_BahatiSing1 voiceActor="" break;
case 171: soundname="BAHATI 15" playSFX=snd_BahatiSing2 voiceActor="" break;
case 172: soundname="BAHATI 16" playSFX=snd_BahatiSing3 voiceActor="" break;
case 173: soundname="BAHATI 17" playSFX=snd_titlescreen3 voiceActor="" break;


case 174: soundname="SOFIA 1" playSFX=snd_sofia1 voiceActor="" break;
case 175: soundname="SOFIA 2" playSFX=snd_sofia2 voiceActor="" break;
case 176: soundname="SOFIA 3" playSFX=snd_sofia3 voiceActor="" break;
case 177: soundname="SOFIA 4" playSFX=snd_sofia4 voiceActor="" break;
case 178: soundname="SOFIA 5" playSFX=snd_sofia5 voiceActor="" break;
case 179: soundname="SOFIA 6" playSFX=snd_sofia6 voiceActor="" break;
case 180: soundname="SOFIA 7" playSFX=snd_sofia7 voiceActor="" break;
case 181: soundname="SOFIA 8" playSFX=snd_sofia8 voiceActor="" break;
case 182: soundname="SOFIA 9" playSFX=snd_sofia9 voiceActor="" break;
case 183: soundname="SOFIA 10" playSFX=snd_sofia10 voiceActor="" break;
case 184: soundname="SOFIA 11" playSFX=snd_sofia11 voiceActor="" break;
case 185: soundname="SOFIA 12" playSFX=snd_sofia12 voiceActor="" break;
case 186: soundname="SOFIA 13" playSFX=snd_sofia13 voiceActor="" break;
case 187: soundname="SOFIA 14" playSFX=snd_sofia14 voiceActor="" break;
case 188: soundname="SOFIA 15" playSFX=snd_sofia20 voiceActor="" break;
case 189: soundname="SOFIA 16" playSFX=snd_sofia21 voiceActor="" break;
case 190: soundname="SOFIA 17" playSFX=snd_SofiaScream voiceActor="" break;
case 191: soundname="SOFIA 18" playSFX=snd_SofiaSing1 voiceActor="" break;
case 192: soundname="SOFIA 19" playSFX=snd_SofiaSing2 voiceActor="" break;
case 193: soundname="SOFIA 20" playSFX=snd_SofiaSing3 voiceActor="" break;
case 194: soundname="SOFIA 21" playSFX=snd_titlescreen4 voiceActor="" break;

case 195: soundname="EN 1" playSFX=snd_enemy1 voiceActor="" break;
case 196: soundname="EN 2" playSFX=snd_enemy2 voiceActor="" break;
case 197: soundname="EN 3" playSFX=snd_enemy3 voiceActor="" break;
case 198: soundname="EN 4" playSFX=snd_enemy4 voiceActor="" break;
case 199: soundname="EN 5" playSFX=snd_enemy5 voiceActor="" break;
case 200: soundname="EN 6" playSFX=snd_enemy6 voiceActor="" break;
case 201: soundname="EN 7" playSFX=snd_deathcry1 voiceActor="" break;
case 202: soundname="EN 8" playSFX=snd_deathcry2 voiceActor="" break;
case 203: soundname="EN 9" playSFX=snd_deathcry3 voiceActor="" break;
case 204: soundname="EN 10" playSFX=snd_deathcryrobot voiceActor="" break;
case 205: soundname="EN 11" playSFX=snd_femenemy1 voiceActor="" break;
case 206: soundname="EN 12" playSFX=snd_femenemy2 voiceActor="" break;
case 207: soundname="EN 13" playSFX=snd_femenemy3 voiceActor="" break;
case 208: soundname="EN 14" playSFX=snd_femenemy4 voiceActor="" break;
case 209: soundname="EN 15" playSFX=snd_femenemy5 voiceActor="" break;
case 210: soundname="EN 16" playSFX=snd_femenemy6 voiceActor="" break;
case 211: soundname="EN 17" playSFX=snd_femenemy7 voiceActor="" break;
case 212: soundname="EN 18" playSFX=snd_femenemy8 voiceActor="" break;
case 213: soundname="EN 19" playSFX=snd_fatburglar voiceActor="" break;
case 214: soundname="EN 20" playSFX=snd_fatburglar2 voiceActor="" break;
case 215: soundname="EN 21" playSFX=snd_buffenemy1 voiceActor="" break;
case 216: soundname="EN 22" playSFX=snd_buffenemy2 voiceActor="" break;
case 217: soundname="EN 23" playSFX=snd_buffenemy3 voiceActor="" break;
case 218: soundname="EN 24" playSFX=snd_msswing1 voiceActor="" break;
case 219: soundname="EN 25" playSFX=snd_msswing2 voiceActor="" break;
case 220: soundname="EN 26" playSFX=snd_ohmecar voiceActor="" break;
case 221: soundname="EN 27" playSFX=snd_harpye voiceActor="" break;
case 222: soundname="EN 28" playSFX=snd_mzombie1 voiceActor="" break;
case 223: soundname="EN 29" playSFX=snd_mzombie2 voiceActor="" break;
case 224: soundname="EN 30" playSFX=snd_mzombie3 voiceActor="" break;
case 225: soundname="EN 31" playSFX=snd_mzombie4 voiceActor="" break;
case 226: soundname="EN 32" playSFX=snd_mzombie5 voiceActor="" break;
case 227: soundname="EN 33" playSFX=snd_fzombie1 voiceActor="" break;
case 228: soundname="EN 34" playSFX=snd_fzombie2 voiceActor="" break;
case 229: soundname="EN 35" playSFX=snd_fzombie3 voiceActor="" break;
case 230: soundname="EN 36" playSFX=snd_fzombie4 voiceActor="" break;
case 231: soundname="EN 37" playSFX=snd_fzombie5 voiceActor="" break;
case 232: soundname="EN 38" playSFX=snd_cat1 voiceActor="" break;
case 233: soundname="EN 39" playSFX=snd_cat2 voiceActor="" break;
case 234: soundname="EN 40" playSFX=snd_cat3 voiceActor="" break;
case 235: soundname="EN 41" playSFX=snd_cobra1 voiceActor="" break;
case 236: soundname="EN 42" playSFX=snd_cobra2 voiceActor="" break;
case 237: soundname="EN 43" playSFX=snd_cobra3 voiceActor="" break;
case 238: soundname="EN 44" playSFX=snd_merman1 voiceActor="" break;
case 239: soundname="EN 45" playSFX=snd_merman2 voiceActor="" break;
case 240: soundname="EN 46" playSFX=snd_merman3 voiceActor="" break;
case 241: soundname="EN 47" playSFX=snd_plant1 voiceActor="" break;
case 242: soundname="EN 48" playSFX=snd_plant2 voiceActor="" break;
case 243: soundname="EN 49" playSFX=snd_plant3 voiceActor="" break;
case 244: soundname="EN 50" playSFX=snd_bear1 voiceActor="" break;
case 245: soundname="EN 51" playSFX=snd_bear2 voiceActor="" break;
case 246: soundname="EN 52" playSFX=snd_bear3 voiceActor="" break;
case 247: soundname="EN 53" playSFX=snd_bear4 voiceActor="" break;
case 248: soundname="EN 54" playSFX=snd_lobster1 voiceActor="" break;
case 249: soundname="EN 55" playSFX=snd_lobster2 voiceActor="" break;
case 250: soundname="EN 56" playSFX=snd_martian1 voiceActor="" break;
case 251: soundname="EN 57" playSFX=snd_martian2 voiceActor="" break;
case 252: soundname="EN 58" playSFX=snd_martian3 voiceActor="" break;

case 253: soundname="BETTY 1" playSFX=snd_betty1 voiceActor="" break;
case 254: soundname="BETTY 2" playSFX=snd_betty2 voiceActor="" break;
case 255: soundname="BETTY 3" playSFX=snd_betty3 voiceActor="" break;
case 256: soundname="BETTY 4" playSFX=snd_betty4 voiceActor="" break;
case 257: soundname="BETTY 5" playSFX=snd_betty5 voiceActor="" break;
case 258: soundname="BETTY 6" playSFX=snd_betty6 voiceActor="" break;
case 259: soundname="BETTY 7" playSFX=snd_betty7 voiceActor="" break;
case 260: soundname="BETTY 8" playSFX=snd_betty8 voiceActor="" break;
case 261: soundname="BETTY 9" playSFX=snd_betty9 voiceActor="" break;
case 262: soundname="BETTY 10" playSFX=snd_betty10 voiceActor="" break;
case 263: soundname="BETTY 11" playSFX=snd_betty11 voiceActor="" break;
case 264: soundname="BETTY 12" playSFX=snd_betty12 voiceActor="" break;
case 265: soundname="BETTY 13" playSFX=snd_betty13 voiceActor="" break;
case 266: soundname="BETTY 14" playSFX=snd_betty14 voiceActor="" break;
case 267: soundname="BETTY 15" playSFX=snd_betty15 voiceActor="" break;

case 268: soundname="OLGA 1" playSFX=snd_olga1 voiceActor="" break;
case 269: soundname="OLGA 2" playSFX=snd_olga2 voiceActor="" break;
case 270: soundname="OLGA 3" playSFX=snd_olga3 voiceActor="" break;
case 271: soundname="OLGA 4" playSFX=snd_olga4 voiceActor="" break;
case 272: soundname="OLGA 5" playSFX=snd_olga5 voiceActor="" break;
case 273: soundname="OLGA 6" playSFX=snd_olga6 voiceActor="" break;
case 274: soundname="OLGA 7" playSFX=snd_olga7 voiceActor="" break;
case 275: soundname="OLGA 8" playSFX=snd_olga8 voiceActor="" break;

case 276: soundname="LADY WOLF 1" playSFX=snd_hwolf1 voiceActor="" break;
case 277: soundname="LADY WOLF 2" playSFX=snd_hwolf2 voiceActor="" break;
case 278: soundname="LADY WOLF 3" playSFX=snd_hwolf3 voiceActor="" break;
case 279: soundname="LADY WOLF 4" playSFX=snd_hwolf4 voiceActor="" break;
case 280: soundname="LADY WOLF 5" playSFX=snd_hwolf5 voiceActor="" break;
case 281: soundname="LADY WOLF 6" playSFX=snd_hwolf6 voiceActor="" break;
case 282: soundname="LADY WOLF 7" playSFX=snd_hwolf7 voiceActor="" break;
case 283: soundname="LADY WOLF 8" playSFX=snd_hwolf8 voiceActor="" break;
case 284: soundname="LADY WOLF 9" playSFX=snd_wolfita1 voiceActor="" break;
case 285: soundname="LADY WOLF 10" playSFX=snd_wolfita2 voiceActor="" break;
case 286: soundname="LADY WOLF 11" playSFX=snd_wolfita3 voiceActor="" break;
case 287: soundname="LADY WOLF 12" playSFX=snd_wolfita4 voiceActor="" break;
case 288: soundname="LADY WOLF 13" playSFX=snd_wolfita5 voiceActor="" break;
case 289: soundname="LADY WOLF 14" playSFX=snd_wolfita6 voiceActor="" break;
case 290: soundname="LADY WOLF 15" playSFX=snd_wolfita7 voiceActor="" break;


case 291: soundname="HARPILDA 1" playSFX=snd_harpy1 voiceActor="" break;
case 292: soundname="HARPILDA 2" playSFX=snd_harpy2 voiceActor="" break;
case 293: soundname="HARPILDA 3" playSFX=snd_harpy3 voiceActor="" break;
case 294: soundname="HARPILDA 4" playSFX=snd_harpy4 voiceActor="" break;
case 295: soundname="HARPILDA 5" playSFX=snd_harpy5 voiceActor="" break;
case 296: soundname="HARPILDA 6" playSFX=snd_harpy6 voiceActor="" break;
case 297: soundname="HARPILDA 7" playSFX=snd_harpy7 voiceActor="" break;
case 298: soundname="HARPILDA 8" playSFX=snd_harpy8 voiceActor="" break;
case 299: soundname="HARPILDA 9" playSFX=snd_harpy9 voiceActor="" break;
case 300: soundname="HARPILDA 10" playSFX=snd_harpy10 voiceActor="" break;
case 301: soundname="HARPILDA 11" playSFX=snd_harpy11 voiceActor="" break;
case 302: soundname="HARPILDA 12" playSFX=snd_harpy12 voiceActor="" break;
case 303: soundname="HARPILDA 13" playSFX=snd_harpy13 voiceActor="" break;


case 304: soundname="C.ROSY 1" playSFX=snd_franki1 voiceActor="" break;
case 305: soundname="C.ROSY 2" playSFX=snd_franki2 voiceActor="" break;
case 306: soundname="C.ROSY 3" playSFX=snd_franki3 voiceActor="" break;
case 307: soundname="C.ROSY 4" playSFX=snd_franki4 voiceActor="" break;
case 308: soundname="C.ROSY 5" playSFX=snd_franki5 voiceActor="" break;
case 309: soundname="C.ROSY 6" playSFX=snd_franki6 voiceActor="" break;
case 310: soundname="C.ROSY 7" playSFX=snd_franki7 voiceActor="" break;
case 311: soundname="C.ROSY 8" playSFX=snd_franki8 voiceActor="" break;
case 312: soundname="C.ROSY 9" playSFX=snd_franki9 voiceActor="" break;
case 313: soundname="C.ROSY 10" playSFX=snd_franki10 voiceActor="" break;
case 314: soundname="C.ROSY 11" playSFX=snd_franki11 voiceActor="" break;
case 315: soundname="C.ROSY 12" playSFX=snd_franki12 voiceActor="" break;

case 316: soundname="DOLORES 1" playSFX=snd_twoheads1 voiceActor="" break;
case 317: soundname="DOLORES 2" playSFX=snd_twoheads2 voiceActor="" break;
case 318: soundname="DOLORES 3" playSFX=snd_twoheads3 voiceActor="" break;
case 319: soundname="DOLORES 4" playSFX=snd_twoheads4 voiceActor="" break;
case 320: soundname="DOLORES 5" playSFX=snd_twoheads5 voiceActor="" break;
case 321: soundname="DOLORES 6" playSFX=snd_twoheads6 voiceActor="" break;
case 322: soundname="DOLORES 7" playSFX=snd_twoheads7 voiceActor="" break;
case 323: soundname="DOLORES 8" playSFX=snd_twoheads8 voiceActor="" break;
case 324: soundname="DOLORES 9" playSFX=snd_twoheads9 voiceActor="" break;
case 325: soundname="DOLORES 10" playSFX=snd_twoheads10 voiceActor="" break;
case 326: soundname="DOLORES 11" playSFX=snd_twoheads11 voiceActor="" break;
case 327: soundname="DOLORES 12" playSFX=snd_twoheads12 voiceActor="" break;


case 328: soundname="ANNA MARI 1" playSFX=snd_ant1 voiceActor="" break;
case 329: soundname="ANNA MARI 2" playSFX=snd_ant2 voiceActor="" break;
case 330: soundname="ANNA MARI 3" playSFX=snd_ant3 voiceActor="" break;
case 331: soundname="ANNA MARI 4" playSFX=snd_ant4 voiceActor="" break;
case 332: soundname="ANNA MARI 5" playSFX=snd_ant5 voiceActor="" break;
case 333: soundname="ANNA MARI 6" playSFX=snd_ant6 voiceActor="" break;
case 334: soundname="ANNA MARI 7" playSFX=snd_ant7 voiceActor="" break;
case 335: soundname="ANNA MARI 8" playSFX=snd_ant8 voiceActor="" break;
case 336: soundname="ANNA MARI 9" playSFX=snd_ant9 voiceActor="" break;
case 337: soundname="ANNA MARI 10" playSFX=snd_ant10 voiceActor="" break;
case 338: soundname="ANNA MARI 11" playSFX=snd_ant11 voiceActor="" break;
case 339: soundname="ANNA MARI 12" playSFX=snd_ant12 voiceActor="" break;
case 340: soundname="ANNA MARI 13" playSFX=snd_ant13 voiceActor="" break;
case 341: soundname="ANNA MARI 14" playSFX=snd_ant14 voiceActor="" break;
case 342: soundname="ANNA MARI 15" playSFX=snd_and12 voiceActor="" break;

case 343: soundname="HATHOR 1" playSFX=snd_pharaoh1 voiceActor="" break;
case 344: soundname="HATHOR 2" playSFX=snd_pharaoh2 voiceActor="" break;
case 345: soundname="HATHOR 3" playSFX=snd_pharaoh3 voiceActor="" break;
case 346: soundname="HATHOR 4" playSFX=snd_pharaoh4 voiceActor="" break;
case 347: soundname="HATHOR 5" playSFX=snd_pharaoh5 voiceActor="" break;
case 348: soundname="HATHOR 6" playSFX=snd_pharaoh6 voiceActor="" break;
case 349: soundname="HATHOR 7" playSFX=snd_pharaoh7 voiceActor="" break;
case 350: soundname="HATHOR 8" playSFX=snd_pharaoh8 voiceActor="" break;
case 351: soundname="HATHOR 9" playSFX=snd_pharaoh9 voiceActor="" break;
case 352: soundname="HATHOR 10" playSFX=snd_pharaoh10 voiceActor="" break;
case 353: soundname="HATHOR 11" playSFX=snd_pharaoh11 voiceActor="" break;
case 354: soundname="HATHOR 12" playSFX=snd_pharaoh12 voiceActor="" break;
case 355: soundname="HATHOR 13" playSFX=snd_pharaoh13 voiceActor="" break;
case 356: soundname="HATHOR 14" playSFX=snd_pharaoh14 voiceActor="" break;

case 357: soundname="ONI SIS 1" playSFX=snd_oni1 voiceActor="" break;
case 358: soundname="ONI SIS 2" playSFX=snd_oni2 voiceActor="" break;
case 359: soundname="ONI SIS 3" playSFX=snd_oni3 voiceActor="" break;
case 360: soundname="ONI SIS 4" playSFX=snd_oni4 voiceActor="" break;
case 361: soundname="ONI SIS 5" playSFX=snd_oni5 voiceActor="" break;
case 362: soundname="ONI SIS 6" playSFX=snd_oni6 voiceActor="" break;
case 363: soundname="ONI SIS 7" playSFX=snd_oni7 voiceActor="" break;
case 364: soundname="ONI SIS 8" playSFX=snd_oni8 voiceActor="" break;
case 365: soundname="ONI SIS 9" playSFX=snd_oni9 voiceActor="" break;
case 366: soundname="ONI SIS 10" playSFX=snd_oni10 voiceActor="" break;
case 367: soundname="ONI SIS 11" playSFX=snd_oni11 voiceActor="" break;
case 368: soundname="ONI SIS 12" playSFX=snd_oni12 voiceActor="" break;
case 369: soundname="ONI SIS 13" playSFX=snd_oni13 voiceActor="" break;


case 370: soundname="KIANDRA 1" playSFX=snd_witch1 voiceActor="" break;
case 371: soundname="KIANDRA 2" playSFX=snd_witch2 voiceActor="" break;
case 372: soundname="KIANDRA 3" playSFX=snd_witch3 voiceActor="" break;
case 373: soundname="KIANDRA 4" playSFX=snd_witch4 voiceActor="" break;
case 374: soundname="KIANDRA 5" playSFX=snd_witch5 voiceActor="" break;
case 375: soundname="KIANDRA 6" playSFX=snd_witch6 voiceActor="" break;
case 376: soundname="KIANDRA 7" playSFX=snd_witch7 voiceActor="" break;
case 377: soundname="KIANDRA 8" playSFX=snd_witch8 voiceActor="" break;
case 378: soundname="KIANDRA 9" playSFX=snd_witch9 voiceActor="" break;
case 379: soundname="KIANDRA 10" playSFX=snd_witch10 voiceActor="" break;


case 380: soundname="DIXIE 1" playSFX=snd_duck1 voiceActor="" break;
case 381: soundname="DIXIE 2" playSFX=snd_duck2 voiceActor="" break;
case 382: soundname="DIXIE 3" playSFX=snd_duck3 voiceActor="" break;
case 383: soundname="DIXIE 4" playSFX=snd_duck4 voiceActor="" break;
case 384: soundname="DIXIE 5" playSFX=snd_duck5 voiceActor="" break;
case 385: soundname="DIXIE 6" playSFX=snd_duck6 voiceActor="" break;
case 386: soundname="DIXIE 7" playSFX=snd_duck7 voiceActor="" break;
case 387: soundname="DIXIE 8" playSFX=snd_duck8 voiceActor="" break;
case 388: soundname="DIXIE 9" playSFX=snd_duck9 voiceActor="" break;
case 389: soundname="DIXIE 10" playSFX=snd_duck10 voiceActor="" break;
case 390: soundname="DIXIE 11" playSFX=snd_duck11 voiceActor="" break;
case 391: soundname="DIXIE 12" playSFX=snd_duck12 voiceActor="" break;


case 392: soundname="CIRCE 1" playSFX=snd_seaweed1 voiceActor="" break;
case 393: soundname="CIRCE 2" playSFX=snd_seaweed2 voiceActor="" break;
case 394: soundname="CIRCE 3" playSFX=snd_seaweed3 voiceActor="" break;
case 395: soundname="CIRCE 4" playSFX=snd_seaweed4 voiceActor="" break;
case 396: soundname="CIRCE 5" playSFX=snd_seaweed5 voiceActor="" break;
case 397: soundname="CIRCE 6" playSFX=snd_seaweed6 voiceActor="" break;
case 398: soundname="CIRCE 7" playSFX=snd_seaweed7 voiceActor="" break;
case 399: soundname="CIRCE 8" playSFX=snd_seaweed8 voiceActor="" break;
case 400: soundname="CIRCE 9" playSFX=snd_seaweed9 voiceActor="" break;
case 401: soundname="CIRCE 10" playSFX=snd_seaweed10 voiceActor="" break;


case 402: soundname="KUINN 1" playSFX=snd_martianb1 voiceActor="" break;
case 403: soundname="KUINN 2" playSFX=snd_martianb2 voiceActor="" break;
case 404: soundname="KUINN 3" playSFX=snd_martianb3 voiceActor="" break;
case 405: soundname="KUINN 4" playSFX=snd_martianb4 voiceActor="" break;
case 406: soundname="KUINN 5" playSFX=snd_martianb5 voiceActor="" break;
case 407: soundname="KUINN 6" playSFX=snd_martianb6 voiceActor="" break;
case 408: soundname="KUINN 7" playSFX=snd_martianb7 voiceActor="" break;
case 409: soundname="KUINN 8" playSFX=snd_martianb8 voiceActor="" break;
case 410: soundname="KUINN 9" playSFX=snd_martianb9 voiceActor="" break;
case 411: soundname="KUINN 10" playSFX=snd_martianb10 voiceActor="" break;
case 412: soundname="KUINN 11" playSFX=snd_martianb11 voiceActor="" break;

case 413: soundname="PRINCE 1" playSFX=snd_prince1 voiceActor="" break;
case 414: soundname="PRINCE 2" playSFX=snd_prince2 voiceActor="" break;
case 415: soundname="PRINCE 3" playSFX=snd_prince3 voiceActor="" break;
case 416: soundname="PRINCE 4" playSFX=snd_prince4 voiceActor="" break;
case 417: soundname="PRINCE 5" playSFX=snd_prince5 voiceActor="" break;
case 418: soundname="PRINCE 6" playSFX=snd_prince6 voiceActor="" break;
case 419: soundname="PRINCE 7" playSFX=snd_prince7 voiceActor="" break;
case 420: soundname="PRINCE 8" playSFX=snd_prince8 voiceActor="" break;
case 421: soundname="PRINCE 9" playSFX=snd_prince9 voiceActor="" break;
case 422: soundname="PRINCE 10" playSFX=snd_prince10 voiceActor="" break;
case 423: soundname="PRINCE 11" playSFX=snd_prince11 voiceActor="" break;
case 424: soundname="PRINCE 12" playSFX=snd_prince12 voiceActor="" break;
case 425: soundname="PRINCE 13" playSFX=snd_prince13 voiceActor="" break;
case 426: soundname="PRINCE 14" playSFX=snd_prince14 voiceActor="" break;
case 427: soundname="PRINCE 15" playSFX=snd_prince15 voiceActor="" break;
case 428: soundname="PRINCE 16" playSFX=snd_prince16 voiceActor="" break;
case 429: soundname="PRINCE 17" playSFX=snd_prince17 voiceActor="" break;
case 430: soundname="PRINCE 18" playSFX=snd_prince18 voiceActor="" break;
case 431: soundname="PRINCE 19" playSFX=snd_prince19 voiceActor="" break;
case 432: soundname="PRINCE 20" playSFX=snd_prince20 voiceActor="" break;
case 433: soundname="PRINCE 21" playSFX=snd_prince21 voiceActor="" break;

case 434: soundname="HAIFA 1" playSFX=snd_genie1 voiceActor="" break;
case 435: soundname="HAIFA 2" playSFX=snd_genie2 voiceActor="" break;
case 436: soundname="HAIFA 3" playSFX=snd_genie3 voiceActor="" break;
case 437: soundname="HAIFA 4" playSFX=snd_genie4 voiceActor="" break;
case 438: soundname="HAIFA 5" playSFX=snd_genie5 voiceActor="" break;
case 439: soundname="HAIFA 6" playSFX=snd_genie6 voiceActor="" break;
case 440: soundname="HAIFA 7" playSFX=snd_genie7 voiceActor="" break;
case 441: soundname="HAIFA 8" playSFX=snd_genie8 voiceActor="" break;
case 442: soundname="HAIFA 9" playSFX=snd_genie9 voiceActor="" break;
case 443: soundname="HAIFA 10" playSFX=snd_genie10 voiceActor="" break;
case 444: soundname="HAIFA 11" playSFX=snd_genie11 voiceActor="" break;
case 445: soundname="HAIFA 12" playSFX=snd_genie12 voiceActor="" break;
case 446: soundname="HAIFA 13" playSFX=snd_genie13 voiceActor="" break;
case 447: soundname="HAIFA 14" playSFX=snd_genie14 voiceActor="" break;


case 448: soundname="MIRROSA 1" playSFX=snd_mirrorlady1 voiceActor="" break;
case 449: soundname="MIRROSA 2" playSFX=snd_mirrorlady2 voiceActor="" break;
case 450: soundname="MIRROSA 3" playSFX=snd_mirrorlady3 voiceActor="" break;
case 451: soundname="MIRROSA 4" playSFX=snd_mirrorlady4 voiceActor="" break;
case 452: soundname="MIRROSA 5" playSFX=snd_mirrorlady5 voiceActor="" break;
case 453: soundname="MIRROSA 6" playSFX=snd_mirrorlady6 voiceActor="" break;
case 454: soundname="MIRROSA 7" playSFX=snd_mirrorlady7 voiceActor="" break;
case 455: soundname="MIRROSA 8" playSFX=snd_mirrorlady8 voiceActor="" break;
case 456: soundname="MIRROSA 9" playSFX=snd_mirrorlady9 voiceActor="" break;
case 457: soundname="MIRROSA 10" playSFX=snd_mirrorlady10 voiceActor="" break;
case 458: soundname="MIRROSA 11" playSFX=snd_mirrorlady11 voiceActor="" break;
case 459: soundname="MIRROSA 12" playSFX=snd_mirrorlady12 voiceActor="" break;
case 460: soundname="MIRROSA 13" playSFX=snd_mirrorlady13 voiceActor="" break;
case 461: soundname="MIRROSA 14" playSFX=snd_mirrorlady14 voiceActor="" break;

case 462: soundname="SYNTHESA 1" playSFX=snd_princess1 voiceActor="" break;
case 463: soundname="SYNTHESA 2" playSFX=snd_princess2 voiceActor="" break;
case 464: soundname="SYNTHESA 3" playSFX=snd_princess3 voiceActor="" break;
case 465: soundname="SYNTHESA 4" playSFX=snd_princess4 voiceActor="" break;
case 466: soundname="SYNTHESA 5" playSFX=snd_princess5 voiceActor="" break;
case 467: soundname="SYNTHESA 6" playSFX=snd_princess6 voiceActor="" break;
case 468: soundname="SYNTHESA 7" playSFX=snd_princess7 voiceActor="" break;
case 469: soundname="SYNTHESA 8" playSFX=snd_princess8 voiceActor="" break;
case 470: soundname="SYNTHESA 9" playSFX=snd_princess9 voiceActor="" break;
case 471: soundname="SYNTHESA 10" playSFX=snd_princess10 voiceActor="" break;
case 472: soundname="SYNTHESA 11" playSFX=snd_princess11 voiceActor="" break;
case 473: soundname="SYNTHESA 12" playSFX=snd_princess12 voiceActor="" break;
case 474: soundname="SYNTHESA 13" playSFX=snd_princess13 voiceActor="" break;
case 475: soundname="SYNTHESA 14" playSFX=snd_princess14 voiceActor="" break;
case 476: soundname="SYNTHESA 15" playSFX=snd_princess15 voiceActor="" break;
case 477: soundname="SYNTHESA 16" playSFX=snd_princess16 voiceActor="" break;
case 478: soundname="SYNTHESA 17" playSFX=snd_princess17 voiceActor="" break;
case 479: soundname="SYNTHESA 18" playSFX=snd_princess18 voiceActor="" break;
case 480: soundname="SYNTHESA 19" playSFX=snd_princess19 voiceActor="" break;
case 481: soundname="SYNTHESA 20" playSFX=snd_princess20 voiceActor="" break;
case 482: soundname="SYNTHESA 21" playSFX=snd_princess21 voiceActor="" break;

case 483: soundname="FIONA 1" playSFX=snd_dragon1 voiceActor="" break;
case 484: soundname="FIONA 2" playSFX=snd_dragon2 voiceActor="" break;
case 485: soundname="FIONA 3" playSFX=snd_dragon3 voiceActor="" break;
case 486: soundname="FIONA 4" playSFX=snd_dragon4 voiceActor="" break;
case 487: soundname="FIONA 5" playSFX=snd_dragon5 voiceActor="" break;
case 488: soundname="FIONA 6" playSFX=snd_dragon6 voiceActor="" break;
case 489: soundname="FIONA 7" playSFX=snd_dragon7 voiceActor="" break;
case 490: soundname="FIONA 8" playSFX=snd_dragon8 voiceActor="" break;
case 491: soundname="FIONA 9" playSFX=snd_dragon9 voiceActor="" break;

case 492: soundname="DR.FRAN 1" playSFX=snd_scientist1 voiceActor="" break;
case 493: soundname="DR.FRAN 2" playSFX=snd_scientist2 voiceActor="" break;
case 494: soundname="DR.FRAN 3" playSFX=snd_scientist3 voiceActor="" break;
case 495: soundname="DR.FRAN 4" playSFX=snd_scientist4 voiceActor="" break;
case 496: soundname="DR.FRAN 5" playSFX=snd_scientist5 voiceActor="" break;
case 497: soundname="DR.FRAN 6" playSFX=snd_scientist6 voiceActor="" break;
case 498: soundname="DR.FRAN 7" playSFX=snd_scientist7 voiceActor="" break;
case 499: soundname="DR.FRAN 8" playSFX=snd_scientist8 voiceActor="" break;
case 500: soundname="DR.FRAN 9" playSFX=snd_scientist9 voiceActor="" break;
case 501: soundname="DR.FRAN 10" playSFX=snd_scientist10 voiceActor="" break;
case 502: soundname="DR.FRAN 11" playSFX=snd_scientist11 voiceActor="" break;
case 503: soundname="DR.FRAN 12" playSFX=snd_scientist12 voiceActor="" break;
case 504: soundname="DR.FRAN 13" playSFX=snd_scientist13 voiceActor="" break;

case 505: soundname="VAN BAD 1" playSFX=snd_dastardly1 voiceActor="" break;
case 506: soundname="VAN BAD 2" playSFX=snd_dastardly2 voiceActor="" break;
case 507: soundname="VAN BAD 3" playSFX=snd_dastardly3 voiceActor="" break;
case 508: soundname="VAN BAD 4" playSFX=snd_dastardly4 voiceActor="" break;
case 509: soundname="VAN BAD 5" playSFX=snd_dastardly5 voiceActor="" break;
case 510: soundname="VAN BAD 6" playSFX=snd_dastardly6 voiceActor="" break;
case 511: soundname="VAN BAD 7" playSFX=snd_dastardly7 voiceActor="" break;
case 512: soundname="VAN BAD 8" playSFX=snd_dastardly8 voiceActor="" break;
case 513: soundname="VAN BAD 9" playSFX=snd_dastardly9 voiceActor="" break;
case 514: soundname="VAN BAD 10" playSFX=snd_dastardly10 voiceActor="" break;
case 515: soundname="VAN BAD 11" playSFX=snd_dastardly11 voiceActor="" break;
case 516: soundname="VAN BAD 12" playSFX=snd_dastardly12 voiceActor="" break;
case 517: soundname="VAN BAD 13" playSFX=snd_dastardly13 voiceActor="" break;
case 518: soundname="VAN BAD 14" playSFX=snd_dastardly14 voiceActor="" break;
case 519: soundname="VAN BAD 15" playSFX=snd_dastardly15 voiceActor="" break;
case 520: soundname="VAN BAD 16" playSFX=snd_dastardly16 voiceActor="" break;
case 521: soundname="VAN BAD 17" playSFX=snd_dastardly17 voiceActor="" break;
case 522: soundname="VAN BAD 18" playSFX=snd_dastardly18 voiceActor="" break;
case 523: soundname="VAN BAD 19" playSFX=snd_dastardly19 voiceActor="" break;
case 524: soundname="VAN BAD 20" playSFX=snd_dastardly20 voiceActor="" break;
case 525: soundname="VAN BAD 21" playSFX=snd_dastardly21 voiceActor="" break;
case 526: soundname="VAN BAD 22" playSFX=snd_dastardly22 voiceActor="" break;
case 527: soundname="VAN BAD 23" playSFX=snd_dastardly23 voiceActor="" break;
case 528: soundname="VAN BAD 24" playSFX=snd_dastardly24 voiceActor="" break;
case 529: soundname="VAN BAD 25" playSFX=snd_dastardly25 voiceActor="" break;
case 530: soundname="VAN BAD 26" playSFX=snd_dastardly26 voiceActor="" break;
case 531: soundname="VAN BAD 27" playSFX=snd_dastardly27 voiceActor="" break;
case 532: soundname="VAN BAD 28" playSFX=snd_dastardly28 voiceActor="" break;
case 533: soundname="VAN BAD 29" playSFX=snd_dastardly29 voiceActor="" break;
case 534: soundname="VAN BAD 30" playSFX=snd_dastardly30 voiceActor="" break;
case 535: soundname="VAN BAD 31" playSFX=snd_dastardly31 voiceActor="" break;

case 536: soundname="F.VAN BAD 1" playSFX=snd_fdas1 voiceActor="" break;
case 537: soundname="F.VAN BAD 2" playSFX=snd_fdas2 voiceActor="" break;
case 538: soundname="F.VAN BAD 3" playSFX=snd_fdas3 voiceActor="" break;
case 539: soundname="F.VAN BAD 4" playSFX=snd_fdas4 voiceActor="" break;
case 540: soundname="F.VAN BAD 5" playSFX=snd_fdas5 voiceActor="" break;
case 541: soundname="F.VAN BAD 6" playSFX=snd_fdas6 voiceActor="" break;
case 542: soundname="F.VAN BAD 7" playSFX=snd_fdas7 voiceActor="" break;
case 543: soundname="F.VAN BAD 8" playSFX=snd_fdas8 voiceActor="" break;
case 544: soundname="F.VAN BAD 9" playSFX=snd_fdas9 voiceActor="" break;
case 545: soundname="F.VAN BAD 10" playSFX=snd_fdas10 voiceActor="" break;
case 546: soundname="F.VAN BAD 11" playSFX=snd_fdas11 voiceActor="" break;
case 547: soundname="F.VAN BAD 12" playSFX=snd_fdas12 voiceActor="" break;
case 548: soundname="F.VAN BAD 13" playSFX=snd_fdas13 voiceActor="" break;
case 549: soundname="F.VAN BAD 14" playSFX=snd_fdas14 voiceActor="" break;
case 550: soundname="F.VAN BAD 15" playSFX=snd_fdas15 voiceActor="" break;
case 551: soundname="F.VAN BAD 16" playSFX=snd_fdas16 voiceActor="" break;
case 552: soundname="F.VAN BAD 17" playSFX=snd_fdas17 voiceActor="" break;
case 553: soundname="F.VAN BAD 18" playSFX=snd_fdas18 voiceActor="" break;
case 554: soundname="F.VAN BAD 19" playSFX=snd_fdas19 voiceActor="" break;
case 555: soundname="F.VAN BAD 20" playSFX=snd_fdas20 voiceActor="" break;
case 556: soundname="F.VAN BAD 21" playSFX=snd_fdas21 voiceActor="" break;
case 557: soundname="F.VAN BAD 22" playSFX=snd_fdas22 voiceActor="" break;
case 558: soundname="F.VAN BAD 23" playSFX=snd_fdas23 voiceActor="" break;
case 559: soundname="F.VAN BAD 24" playSFX=snd_fdas24 voiceActor="" break;
case 560: soundname="F.VAN BAD 25" playSFX=snd_fdas25 voiceActor="" break;
case 561: soundname="F.VAN BAD 26" playSFX=snd_fdas26 voiceActor="" break;
case 562: soundname="F.VAN BAD 27" playSFX=snd_fdas27 voiceActor="" break;
case 563: soundname="F.VAN BAD 28" playSFX=snd_fdas28 voiceActor="" break;
case 564: soundname="F.VAN BAD 29" playSFX=snd_fdas29 voiceActor="" break;

case 565: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 566: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 567: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 568: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 569: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 570: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 571: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 572: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 573: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 574: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 575: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 576: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 577: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 578: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 579: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 580: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 581: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 582: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 583: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 584: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 585: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 586: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 587: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 588: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 589: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 590: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 591: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 592: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 593: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 594: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 595: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 596: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 597: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 598: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;
case 599: soundname="EN 9" playSFX=snd_fatburglar2 voiceActor="" break;

}
}