function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // object49
	global.__objectDepths[1] = -99999999; // oControl
	global.__objectDepths[2] = -99999998; // oBlackFX
	global.__objectDepths[3] = 0; // oPlayer
	global.__objectDepths[4] = 0; // oAnimEditor
	global.__objectDepths[5] = 0; // oSolid
	global.__objectDepths[6] = 0; // oBlock0
	global.__objectDepths[7] = 0; // oBlock
	global.__objectDepths[8] = 0; // oSelfAtk
	global.__objectDepths[9] = 0; // oEnSpawn
	global.__objectDepths[10] = 0; // oProjectile
	global.__objectDepths[11] = 0; // parEnemy
	global.__objectDepths[12] = 0; // ParCharPhys
	global.__objectDepths[13] = 0; // oViewTarget
	global.__objectDepths[14] = 0; // oLevelSelect
	global.__objectDepths[15] = 100000; // oShadowFX
	global.__objectDepths[16] = 0; // oShadowOnly
	global.__objectDepths[17] = 0; // oFlashFX
	global.__objectDepths[18] = 0; // oDisappearPart
	global.__objectDepths[19] = 1000000; // oExplosion
	global.__objectDepths[20] = 0; // oEnemySpawner
	global.__objectDepths[21] = 0; // oFakeSpawner
	global.__objectDepths[22] = 0; // oCamLock
	global.__objectDepths[23] = 0; // oEnemyVisibleCheckLeft
	global.__objectDepths[24] = 0; // oEnemyVisibleCheckRight
	global.__objectDepths[25] = 0; // oHeight32
	global.__objectDepths[26] = 0; // oHeight64
	global.__objectDepths[27] = 0; // oHeight48
	global.__objectDepths[28] = 0; // oHeight128
	global.__objectDepths[29] = 0; // object84
	global.__objectDepths[30] = 0; // oEnemy1
	global.__objectDepths[31] = 0; // oFemBurglar
	global.__objectDepths[32] = 0; // oFatBurglar
	global.__objectDepths[33] = 0; // oSneak
	global.__objectDepths[34] = 0; // oSwing
	global.__objectDepths[35] = 0; // oRobot
	global.__objectDepths[36] = 0; // oRobotLaser
	global.__objectDepths[37] = 0; // oEnemyTemplate
	global.__objectDepths[38] = 0; // oSandbag
	global.__objectDepths[39] = 0; // oBoxer
	global.__objectDepths[40] = 0; // oGalsia
	global.__objectDepths[41] = 0; // oMsDummy
	global.__objectDepths[42] = 10000; // oAreaSpawner
	global.__objectDepths[43] = 0; // oBoss1
	global.__objectDepths[44] = 0; // oBarrel
	global.__objectDepths[45] = 0; // oBananaPeel
	global.__objectDepths[46] = 0; // oBarrelRoll
	global.__objectDepths[47] = 0; // object90
	global.__objectDepths[48] = 0; // oTrash
	global.__objectDepths[49] = 0; // oCone
	global.__objectDepths[50] = 0; // oMenuStand
	global.__objectDepths[51] = 0; // oCrusher
	global.__objectDepths[52] = 1000000; // oElecFloor
	global.__objectDepths[53] = 1000000; // oBurnFloor
	global.__objectDepths[54] = 1000000; // oIceFloor
	global.__objectDepths[55] = 1000000; // oTreadmill
	global.__objectDepths[56] = 0; // oShockSkip
	global.__objectDepths[57] = 0; // oCar
	global.__objectDepths[58] = 0; // oCarUnused
	global.__objectDepths[59] = 0; // oDoorTrap
	global.__objectDepths[60] = 99999; // oPizza
	global.__objectDepths[61] = 99999; // oDrink
	global.__objectDepths[62] = 99999; // oApple
	global.__objectDepths[63] = 99999; // oChocolate
	global.__objectDepths[64] = 99999; // oBanana
	global.__objectDepths[65] = 99999; // oCake
	global.__objectDepths[66] = 99999; // oTea
	global.__objectDepths[67] = 99999; // oGum
	global.__objectDepths[68] = 99999; // oBurger
	global.__objectDepths[69] = 99999; // oMeat
	global.__objectDepths[70] = 99999; // oDonut
	global.__objectDepths[71] = 99999; // oFries
	global.__objectDepths[72] = 99999; // oHotDog
	global.__objectDepths[73] = 99999; // oSuperItem
	global.__objectDepths[74] = 0; // oBomb
	global.__objectDepths[75] = 0; // oBat
	global.__objectDepths[76] = 0; // oStaff
	global.__objectDepths[77] = 0; // oGun
	global.__objectDepths[78] = 0; // oTommyGun
	global.__objectDepths[79] = 0; // oBazooka
	global.__objectDepths[80] = 0; // oHammer
	global.__objectDepths[81] = 0; // oAxe
	global.__objectDepths[82] = 0; // oKnife
	global.__objectDepths[83] = 0; // oRapier
	global.__objectDepths[84] = 0; // oPipe
	global.__objectDepths[85] = 0; // oKatana
	global.__objectDepths[86] = 0; // oRobotArm
	global.__objectDepths[87] = 0; // oFlameArm
	global.__objectDepths[88] = 0; // object96
	global.__objectDepths[89] = 0; // oHeliumTank
	global.__objectDepths[90] = 0; // oSword
	global.__objectDepths[91] = 0; // oTPoseViva
	global.__objectDepths[92] = 99999; // oGemstone
	global.__objectDepths[93] = 0; // oEnemyIDModifier_01
	global.__objectDepths[94] = 0; // oEnemyIDModifier_02
	global.__objectDepths[95] = 0; // oWaveSetup1
	global.__objectDepths[96] = 0; // oFallHole
	global.__objectDepths[97] = 0; // oAnimFX
	global.__objectDepths[98] = 0; // obj_palette_manager
	global.__objectDepths[99] = 0; // obj_basic_example
	global.__objectDepths[100] = 0; // obj_dummy
	global.__objectDepths[101] = 0; // obj_gradual_example
	global.__objectDepths[102] = 0; // obj_single_replace_example
	global.__objectDepths[103] = 0; // obj_full_fade_example
	global.__objectDepths[104] = 0; // obj_desaturate_example
	global.__objectDepths[105] = 0; // obj_tile_example
	global.__objectDepths[106] = 0; // obj_tile_swapper_start
	global.__objectDepths[107] = 0; // obj_tile_swapper_end
	global.__objectDepths[108] = 0; // oAffTag0
	global.__objectDepths[109] = 0; // oAffTag1
	global.__objectDepths[110] = 0; // oAffTag2
	global.__objectDepths[111] = 0; // oPlayerTag


	global.__objectNames[0] = "object49";
	global.__objectNames[1] = "oControl";
	global.__objectNames[2] = "oBlackFX";
	global.__objectNames[3] = "oPlayer";
	global.__objectNames[4] = "oAnimEditor";
	global.__objectNames[5] = "oSolid";
	global.__objectNames[6] = "oBlock0";
	global.__objectNames[7] = "oBlock";
	global.__objectNames[8] = "oSelfAtk";
	global.__objectNames[9] = "oEnSpawn";
	global.__objectNames[10] = "oProjectile";
	global.__objectNames[11] = "parEnemy";
	global.__objectNames[12] = "ParCharPhys";
	global.__objectNames[13] = "oViewTarget";
	global.__objectNames[14] = "oLevelSelect";
	global.__objectNames[15] = "oShadowFX";
	global.__objectNames[16] = "oShadowOnly";
	global.__objectNames[17] = "oFlashFX";
	global.__objectNames[18] = "oDisappearPart";
	global.__objectNames[19] = "oExplosion";
	global.__objectNames[20] = "oEnemySpawner";
	global.__objectNames[21] = "oFakeSpawner";
	global.__objectNames[22] = "oCamLock";
	global.__objectNames[23] = "oEnemyVisibleCheckLeft";
	global.__objectNames[24] = "oEnemyVisibleCheckRight";
	global.__objectNames[25] = "oHeight32";
	global.__objectNames[26] = "oHeight64";
	global.__objectNames[27] = "oHeight48";
	global.__objectNames[28] = "oHeight128";
	global.__objectNames[29] = "object84";
	global.__objectNames[30] = "oEnemy1";
	global.__objectNames[31] = "oFemBurglar";
	global.__objectNames[32] = "oFatBurglar";
	global.__objectNames[33] = "oSneak";
	global.__objectNames[34] = "oSwing";
	global.__objectNames[35] = "oRobot";
	global.__objectNames[36] = "oRobotLaser";
	global.__objectNames[37] = "oEnemyTemplate";
	global.__objectNames[38] = "oSandbag";
	global.__objectNames[39] = "oBoxer";
	global.__objectNames[40] = "oGalsia";
	global.__objectNames[41] = "oMsDummy";
	global.__objectNames[42] = "oAreaSpawner";
	global.__objectNames[43] = "oBoss1";
	global.__objectNames[44] = "oBarrel";
	global.__objectNames[45] = "oBananaPeel";
	global.__objectNames[46] = "oBarrelRoll";
	global.__objectNames[47] = "object90";
	global.__objectNames[48] = "oTrash";
	global.__objectNames[49] = "oCone";
	global.__objectNames[50] = "oMenuStand";
	global.__objectNames[51] = "oCrusher";
	global.__objectNames[52] = "oElecFloor";
	global.__objectNames[53] = "oBurnFloor";
	global.__objectNames[54] = "oIceFloor";
	global.__objectNames[55] = "oTreadmill";
	global.__objectNames[56] = "oShockSkip";
	global.__objectNames[57] = "oCar";
	global.__objectNames[58] = "oCarUnused";
	global.__objectNames[59] = "oDoorTrap";
	global.__objectNames[60] = "oPizza";
	global.__objectNames[61] = "oDrink";
	global.__objectNames[62] = "oApple";
	global.__objectNames[63] = "oChocolate";
	global.__objectNames[64] = "oBanana";
	global.__objectNames[65] = "oCake";
	global.__objectNames[66] = "oTea";
	global.__objectNames[67] = "oGum";
	global.__objectNames[68] = "oBurger";
	global.__objectNames[69] = "oMeat";
	global.__objectNames[70] = "oDonut";
	global.__objectNames[71] = "oFries";
	global.__objectNames[72] = "oHotDog";
	global.__objectNames[73] = "oSuperItem";
	global.__objectNames[74] = "oBomb";
	global.__objectNames[75] = "oBat";
	global.__objectNames[76] = "oStaff";
	global.__objectNames[77] = "oGun";
	global.__objectNames[78] = "oTommyGun";
	global.__objectNames[79] = "oBazooka";
	global.__objectNames[80] = "oHammer";
	global.__objectNames[81] = "oAxe";
	global.__objectNames[82] = "oKnife";
	global.__objectNames[83] = "oRapier";
	global.__objectNames[84] = "oPipe";
	global.__objectNames[85] = "oKatana";
	global.__objectNames[86] = "oRobotArm";
	global.__objectNames[87] = "oFlameArm";
	global.__objectNames[88] = "object96";
	global.__objectNames[89] = "oHeliumTank";
	global.__objectNames[90] = "oSword";
	global.__objectNames[91] = "oTPoseViva";
	global.__objectNames[92] = "oGemstone";
	global.__objectNames[93] = "oEnemyIDModifier_01";
	global.__objectNames[94] = "oEnemyIDModifier_02";
	global.__objectNames[95] = "oWaveSetup1";
	global.__objectNames[96] = "oFallHole";
	global.__objectNames[97] = "oAnimFX";
	global.__objectNames[98] = "obj_palette_manager";
	global.__objectNames[99] = "obj_basic_example";
	global.__objectNames[100] = "obj_dummy";
	global.__objectNames[101] = "obj_gradual_example";
	global.__objectNames[102] = "obj_single_replace_example";
	global.__objectNames[103] = "obj_full_fade_example";
	global.__objectNames[104] = "obj_desaturate_example";
	global.__objectNames[105] = "obj_tile_example";
	global.__objectNames[106] = "obj_tile_swapper_start";
	global.__objectNames[107] = "obj_tile_swapper_end";
	global.__objectNames[108] = "oAffTag0";
	global.__objectNames[109] = "oAffTag1";
	global.__objectNames[110] = "oAffTag2";
	global.__objectNames[111] = "oPlayerTag";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
