function keyno_check() {
	if keyNo=0 keyNoCheck=" "
	if keyNo=1 keyNoCheck="A"
	if keyNo=2 keyNoCheck="B"
	if keyNo=3 keyNoCheck="C"
	if keyNo=4 keyNoCheck="D"
	if keyNo=5 keyNoCheck="E"
	if keyNo=6 keyNoCheck="F"
	if keyNo=7 keyNoCheck="G"
	if keyNo=8 keyNoCheck="H"
	if keyNo=9 keyNoCheck="I"
	if keyNo=10 keyNoCheck="J"
	if keyNo=11 keyNoCheck="K"
	if keyNo=12 keyNoCheck="L"
	if keyNo=13 keyNoCheck="M"
	if keyNo=14 keyNoCheck="N"
	if keyNo=15 keyNoCheck="O"
	if keyNo=16 keyNoCheck="P"
	if keyNo=17 keyNoCheck="Q"
	if keyNo=18 keyNoCheck="R"
	if keyNo=19 keyNoCheck="S"
	if keyNo=20 keyNoCheck="T"
	if keyNo=21 keyNoCheck="U"
	if keyNo=22 keyNoCheck="V"
	if keyNo=23 keyNoCheck="W"
	if keyNo=24 keyNoCheck="X"
	if keyNo=25 keyNoCheck="Y"
	if keyNo=26 keyNoCheck="Z"
	if keyNo=27 keyNoCheck="1"
	if keyNo=28 keyNoCheck="2"
	if keyNo=29 keyNoCheck="3"
	if keyNo=30 keyNoCheck="4"
	if keyNo=31 keyNoCheck="5"
	if keyNo=32 keyNoCheck="6"
	if keyNo=33 keyNoCheck="7"
	if keyNo=34 keyNoCheck="8"
	if keyNo=35 keyNoCheck="9"
	if keyNo=36 keyNoCheck="0"
	if keyNo=37 keyNoCheck="("
	if keyNo=38 keyNoCheck=")"
	if keyNo=39 keyNoCheck="_"
	if keyNo=40 keyNoCheck="/"
	if keyNo=41 keyNoCheck="\""
	if keyNo=42 keyNoCheck="'"
	if keyNo=43 keyNoCheck="."
	if keyNo=44 keyNoCheck="-"
	if keyNo=45 keyNoCheck="+"
	if keyNo=46 keyNoCheck="%"
	if keyNo=47 keyNoCheck="©"
	if keyNo=48 keyNoCheck="∞"



}
